### ISSUE TITLE
Clean-up for this repo

### ISSUE THREAD

**Issue by mcmonojit** [bhavinjawade/Advanced-Data-Structures-with-Python#10]
**#** When this repository is present in a **local computer** or if an user downloads this repo for **offline** use it is confusing to 
           find the explanation document of a particular algorithm or data structure.

**Solution:** Put each algorithm / data structure file and its's corresponding explanation file into a folder with the same name as the algorithm / data structure.

**Comment by bhavinjawade** [comment]
Sounds good. @mcmonojit.
Go ahead with this.

**Comment by mcmonojit** [comment]
Thanks. I am working on it.

**Comment by bhavinjawade** [comment]
Looks Good. I have merged your PR. closing this issue.

**Comment by mcmonojit** [comment]
@bhavinjawade , can you please add the label **hacktoberfest-accepted** to my PR.
